add swaks doc & install script for sending mail via iRedMail smtp service

diff --git a/scripts/iredmail-conf b/scripts/iredmail-conf
--- a/scripts/iredmail-conf
+++ b/scripts/iredmail-conf
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+## TODO : Find a way to use a config file to set the variables of iRedMail installation screens
+
 ############
 ## COLORS ##
 ############
@@ -47,10 +49,12 @@ fi
 # Install the dependencies
 InstallDependencies() {
 	printf "${c__fctName}Install the dependencies${nocolor}\n"
-	apt update
-	apt upgrade
-	apt install gzip gnupg2 wget -y
-
+	apt update && apt upgrade && apt install gzip gnupg2 wget -y
+	local test=$?
+	if [ $test -ne 0 ]; then
+		printf "${c__error}The installation of dependencies failed${nocolor}\n"
+		return 1
+	fi
 	return 0
 }
 
@@ -58,11 +62,13 @@ InstallDependencies() {
 # Install the repository
 InstallRepository() {
 	printf "${c__fctName}Install the repository${nocolor}\n"
-	# Download the repository
-	wget https://github.com/iredmail/iRedMail/archive/refs/tags/1.6.3.tar.gz
-	# Extract the repository
-	tar zxf 1.6.3.tar.gz
-
+	# Download & Extract the repository
+	wget https://github.com/iredmail/iRedMail/archive/refs/tags/1.6.3.tar.gz && tar zxf 1.6.3.tar.gz
+	local test=$?
+	if [ $test -ne 0 ]; then
+		printf "${c__error}The download or extraction failed${nocolor}\n"
+		return 1
+	fi
 	return 0
 }
 
@@ -76,6 +82,9 @@ StartIRedMailInstall() {
 	if [ $test -ne 0 ]; then
 		printf "${c__error}The installation failed${nocolor}\n"
 		return 1
+	else
+		printf "${c__success}The installation is finished${nocolor}\n"
+		return 0
 	fi
 }
 
@@ -96,5 +105,19 @@ StartIRedMailInstall
 if [ $? -ne 0 ]; then
 	exit 1
 else
+	printf "${c__fctName}Backup the config file${nocolor}\n"
+	mv /root/iRedMail/config /root/iRedMail/config.bak
+	test_mv=$?
+	if [ $test_mv -ne 0 ]; then
+		printf "${c__error}The backup of the config file failed${nocolor}\n"
+		exit 1
+	fi
+	gpg -c /root/iRedMail/config.bak
+	test_gpg=$?
+	if [ $test_gpg -ne 0 ]; then
+		printf "${c__error}The encryption of the config file failed${nocolor}\n"
+		exit 1
+	fi
+	printf "${c__fctName}Reboot the server ...${nocolor}\n"
 	reboot
 fi
